import axios from 'axios';
import Cookies from 'js-cookie';

// Define the URL of your authentication server and the authorization token (if you have one).
// const authBaseUrl = 'http://localhost:8080/';
const authBaseUrl = 'http://knot.westeurope.cloudapp.azure.com/experience-api/';
const authAuthorizationToken = `Bearer ${Cookies.get('access_token')}`;

// Configure Axios with the base URL and authorization header.
export const axiosExperience = axios.create({
  baseURL: authBaseUrl,
  headers: {
    Authorization: authAuthorizationToken,
  },
});

const authBaseUrlMicrosoft = 'https://graph.microsoft.com/v1.0/';
const authAuthorizationTokenMicrosoft = 'Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6InBpem1VR2ZTS1p3UWw1VWtWWkMtbDlqNDNTM0QtTjZqOUNHMWJxS1pGaHMiLCJhbGciOiJSUzI1NiIsIng1dCI6IjlHbW55RlBraGMzaE91UjIybXZTdmduTG83WSIsImtpZCI6IjlHbW55RlBraGMzaE91UjIybXZTdmduTG83WSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zMDQ4ZGM4Ny00M2YwLTQxMDAtOWFjYi1hZTE5NzFjNzkzOTUvIiwiaWF0IjoxNjk4MDU1MjA4LCJuYmYiOjE2OTgwNTUyMDgsImV4cCI6MTY5ODE0MTkwOCwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsiYzEiLCJjMiJdLCJhaW8iOiJBVlFBcS84VUFBQUFyS2tyNWhIMUx5NlJpczFQWno5MUQ3aVlWZTd0TFl3Y3dYRDlGWVdCNzkyYWlFTWE3bTk1R3JXdXJZRi84dWQyK2F3ODBpOStZS3h3RTlqTndqcTVINXAzd2M3di9wZ1EySWVibFhtR2JqMD0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIEV4cGxvcmVyIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IkNyZXNwbyBDYW1icmEiLCJnaXZlbl9uYW1lIjoiQ2FybG9zIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjEzLjQuMTkuMjUzIiwibmFtZSI6IkNhcmxvcyBDcmVzcG8gQ2FtYnJhIiwib2lkIjoiNTc2OWE5MzgtZjcxMC00Njc5LWFmYzYtNDYwNDk2YzZjZjdkIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTI5MTU5OTcxMTYtNDEzMTYwMzAyOS0xNzg5MjA3NzkzLTgxNDk0NSIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMjg5NzYzQUFDIiwicmgiOiIwLkFRVUFoOXhJTVBCREFFR2F5NjRaY2NlVGxRTUFBQUFBQUFBQXdBQUFBQUFBQUFBRkFGOC4iLCJzY3AiOiJDYWxlbmRhcnMuUmVhZFdyaXRlIENoYXQuUmVhZCBDaGF0LlJlYWRCYXNpYyBDb250YWN0cy5SZWFkV3JpdGUgRGV2aWNlLlJlYWQuQWxsIERldmljZUxvY2FsQ3JlZGVudGlhbC5SZWFkLkFsbCBEZXZpY2VMb2NhbENyZWRlbnRpYWwuUmVhZEJhc2ljLkFsbCBEZXZpY2VNYW5hZ2VtZW50Q29uZmlndXJhdGlvbi5SZWFkLkFsbCBEZXZpY2VNYW5hZ2VtZW50Q29uZmlndXJhdGlvbi5SZWFkV3JpdGUuQWxsIERldmljZU1hbmFnZW1lbnRNYW5hZ2VkRGV2aWNlcy5SZWFkLkFsbCBEZXZpY2VNYW5hZ2VtZW50TWFuYWdlZERldmljZXMuUmVhZFdyaXRlLkFsbCBEZXZpY2VNYW5hZ2VtZW50UkJBQy5SZWFkLkFsbCBEZXZpY2VNYW5hZ2VtZW50U2VydmljZUNvbmZpZy5SZWFkLkFsbCBEaXJlY3RvcnkuUmVhZC5BbGwgRGlyZWN0b3J5LlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZFdyaXRlLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIElkZW50aXR5Umlza0V2ZW50LlJlYWQuQWxsIE1haWwuUmVhZCBNYWlsLlJlYWRXcml0ZSBNYWlsYm94U2V0dGluZ3MuUmVhZFdyaXRlIE5vdGVzLlJlYWRXcml0ZS5BbGwgb3BlbmlkIFBlb3BsZS5SZWFkIFBsYWNlLlJlYWQgUHJlc2VuY2UuUmVhZCBQcmVzZW5jZS5SZWFkLkFsbCBQcmludGVyU2hhcmUuUmVhZEJhc2ljLkFsbCBQcmludEpvYi5DcmVhdGUgUHJpbnRKb2IuUmVhZEJhc2ljIHByb2ZpbGUgUmVwb3J0cy5SZWFkLkFsbCBTaXRlcy5SZWFkV3JpdGUuQWxsIFRhc2tzLlJlYWRXcml0ZSBVc2VyLlJlYWQgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIFVzZXIuUmVhZFdyaXRlLkFsbCBlbWFpbCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6IlB3MG9MRjNnejRQVHkzTVBnZGtfLWFpSUw4Vmp1blRhcjFHTjlYSUtjY2MiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiIzMDQ4ZGM4Ny00M2YwLTQxMDAtOWFjYi1hZTE5NzFjNzkzOTUiLCJ1bmlxdWVfbmFtZSI6ImNjcmVzcGNhQGVtZWFsLm50dGRhdGEuY29tIiwidXBuIjoiY2NyZXNwY2FAZW1lYWwubnR0ZGF0YS5jb20iLCJ1dGkiOiJYWHI2bGhNNVNrYWJNa3JvQmFBTUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX2NjIjpbIkNQMSJdLCJ4bXNfc3NtIjoiMSIsInhtc19zdCI6eyJzdWIiOiJHQVdZY1cwby1Ib3ZoRmRmYUZycTJPb2lfNmlRaWt3QjF2SVdENjVVNjdJIn0sInhtc190Y2R0IjoxMzU0MDMzOTMyLCJ4bXNfdGRiciI6IkVVIn0.Zmzu4YFf5VsJIbvR4Ga8jOyZAGRQSSucOAyas7j6vJp_b5dyI156RjbThI21T5ZlF0NHWVfJmgdPHsq5S56t6NNpFW8PzxBYtMTIEQfdIfJmW2ndgdlQA0oVe0VXkYXS9BesqToqzn_3KoklxtXqTntSs7gZ5f16z2a-Ypq_cuV5FkcSM4wW48ZSN7OM8GL9xwg74CRAKm1kFjj1pRhGYVtEOOXDLk3gIquzuELaVj8GjkOylzG0nGlBNTC0pkhoGtvSRSOrJAECYZfOgQ8iY0g4zhII9NU5L1EUe8D_rQvB1rtgLqvUkl5RIHmPMwAzU0cjtpKxx8b-s0K_5l5N4g';

// Configure Axios with the base URL and authorization header.
export const axiosMicrosoft = axios.create({
  baseURL: authBaseUrlMicrosoft,
  headers: {
    Accept: 'application/json',
    Authorization: authAuthorizationTokenMicrosoft,
  },
});

const authBaseUrlAPIGithub = 'https://api.github.com/';

// Configure Axios with the base URL and authorization header.
export const axiosAPIGithub = axios.create({
  baseURL: authBaseUrlAPIGithub,
  headers: {
    Accept: 'application/vnd.github+json',
    Authorization: authAuthorizationToken,
  },
});
